RestaurantFinder/urls.py
from django.conf import settings
from django.conf.urls.static import static

"""
URL configuration for RestaurantFinder project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("main.urls")),
    path("admin/", admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

urlpatterns = [
    path("login_register", views.loginRegisterPage, name='login_register'),
    path("", views.homePage, name='home'),
    path("login/", views.loginPage, name='login'),
    path("logout/", views.logoutUser, name='logout'),
    path("signup/", views.signupPage, name='signup'),
    path("info/", views.infoPage, name='info'),
    path("aboutus/", views.aboutUsPage, name='about'),
    path("contact/", views.contactPage, name='contact'),
    path("userprofile/", views.userprofilePage, name='profile'),
    path("reviews/", views.reviewsPage, name='reviews'),
    path("editprofile/", views.editprofilePage, name='editP'),
    path('reset_password/', auth_views.PasswordResetView.as_view(
        template_name="main/registration/password_reset_form.html",
        email_template_name="main/registration/password_reset_email.html",
        subject_template_name="main/registration/password_reset_subject.txt"),
        name='password_reset'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(
        template_name="main/registration/password_reset_done.html"),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name="main/registration/password_reset_confirm.html"),
        name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name="main/registration/password_reset_complete.html"),
        name='password_reset_complete'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class Media(models.Model):
    file = models.ImageField(upload_to='media/')


class User(AbstractUser):
    email = models.EmailField("Email", max_length=150, unique=True)
    username = models.CharField("Username", max_length=20, unique=True)
    about = models.TextField(null=True, blank=True)
    avatar = models.ForeignKey(Media, on_delete=models.DO_NOTHING, null=True, blank=True)
    date_joined = models.DateField("Date Joined", auto_now_add=True)


class Restaurant(models.Model):
    name = models.CharField(max_length=50)
    content = models.TextField(null=True, blank=True)
    location = models.TextField(null=True, blank=True)


class Review(models.Model):
    RATING_CHOICES = [
        (1.0, '★☆☆☆☆'),
        (2.0, '★★☆☆☆'),
        (3.0, '★★★☆☆'),
        (4.0, '★★★★☆'),
        (5.0, '★★★★★'),
    ]

    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    content = models.TextField()
    rating = models.FloatField(choices=RATING_CHOICES)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)

main/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import get_user_model
from .models import *

User = get_user_model()
class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

class UserUpdateForm(forms.ModelForm):
    avatar = forms.ImageField(required=False)
    class Meta:
        model = User
        fields = ['username', 'about', 'first_name', 'last_name']
        widgets = {
            'first_name': forms.TextInput(attrs={'class':'name-field', 'placeholder': 'Enter First Name'}),
            'last_name': forms.TextInput(attrs={'class':'name-field', 'placeholder': 'Enter Last Name'}),
            'username': forms.TextInput(attrs={'placeholder': 'Enter new username'}),
            'about': forms.Textarea(attrs={'placeholder': 'Tell us more about yourself', 'rows': '4'}),
        }

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(),
            'email': forms.EmailInput(),
            'first_name': forms.TextInput(),
            'last_name': forms.TextInput(),
            'password1': forms.PasswordInput(),
            'password2': forms.PasswordInput(),
        }

class ResetPassForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        widgets = {
            'username': forms.TextInput(attrs={'class':'search', 'placeholder':'Username'}),
            'email': forms.EmailInput(attrs={'class':'search', 'placeholder':'Email'}),
            'password': forms.PasswordInput(attrs={'class':'search', 'placeholder':'New Password'}),
        }

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['content', 'rating']
        widgets = {
            'content': forms.Textarea(attrs={'class':'form-input', 'placeholder':'Write your review here...'}),
        }

main/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from .forms import *
from .models import Media
import os
import requests
import uuid
import dotenv

dotenv.load_dotenv()

# Create your views here.

def getRestaurantLogo(query):
    query = query.replace(" ", "%20")

    endpoint = "https://api.brandfetch.io/v2/search/" + query
    headers = {
        "Authorization": os.getenv("logoAPI"),
    }

    response = requests.get(endpoint, headers=headers)
    data = response.json()
    fileted_data = []

    fields_to_include = ['name', 'icon', 'logo']
    for suggestion in data:
        filtered_suggestion = {key: suggestion.get(key) for key in fields_to_include if suggestion.get(key) != None}
        if filtered_suggestion.get("icon") or filtered_suggestion.get("logo"):
            fileted_data.append(filtered_suggestion)

    return fileted_data[0].get("logo") if fileted_data[0].get("logo") else fileted_data[0].get("icon")

    

def findRestaurants(query, limit):
    endpoint = "https://api.mapbox.com/search/searchbox/v1/suggest"
    access_token = os.getenv("locationAPI")
    session_token = uuid.uuid4()

    params = {
        "access_token": access_token,
        "session_token": session_token,
        "q": query,
        "limit": 10
    }

    response = requests.get(endpoint, params=params)
    data = response.json()

    restaurant_suggestions = [suggestion for suggestion in data["suggestions"] if suggestion.get('maki') == 'restaurant' and suggestion.get('context', {}).get('country', {}).get('name') == 'Canada']
    restaurant_suggestions = restaurant_suggestions[:limit]
    filtered_restaurant_suggestions = []

    fields_to_include = ['name', 'address', 'full_address', 'place_formatted']
    for suggestion in restaurant_suggestions:
        filtered_suggestion = {key: suggestion[key] for key in fields_to_include}
        filtered_suggestion["image"] = getRestaurantLogo(filtered_suggestion.get("name"))
        filtered_restaurant_suggestions.append(filtered_suggestion)

    return filtered_restaurant_suggestions

def homePage(request):
    user = request.user

    q = request.GET.get('q') if (request.GET.get('q') != None) else 'tim'
    restaurants = findRestaurants(query=q, limit=6)

    context = {'user': user, "restaurants": restaurants}
    return render(request, "main/home.html", context)


def loginRegisterPage(request):
    user = request.user
    login_form = LoginForm()
    register_form = form = SignupForm()
    context = {'login_form': login_form,
               'register_form': register_form, 'user': user}
    return render(request, 'main/login_register.html', context)


def loginPage(request):
    user = request.user
    if request.method == 'POST':
        form = LoginForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home')
    return redirect('login_register')

def signupPage(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
        else:
            return redirect('login_register')
    else:
        return redirect('home')


def infoPage(request):
    user = request.user
    form = ReviewForm(request.POST or None)
    context = {'user': user, 'form': form}
    return render(request, "main/info.html", context)


def aboutUsPage(request):
    context = {}
    return render(request, "main/aboutus.html", context)


def contactPage(request):
    context = {}
    return render(request, "main/contact.html", context)


def userprofilePage(request):
    user = request.user
    context = {'user': user}
    return render(request, "main/userprofile.html", context)

def reviewsPage(request):
    context = {}
    return render(request, "main/reviews.html", context)

def editprofilePage(request):
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, request.FILES,
                              instance=request.user)
        if form.is_valid():
            user = form.save(commit=False)  # Don't save the User instance yet

            # Save the uploaded image in Media model
            if 'avatar' in request.FILES:  # Check if avatar is being updated
                file = request.FILES['avatar']
                file.name = f"{user.username}.png"
                try:
                    os.remove(f"./media/media/{user.username}.png")

                except:
                    pass
                avatar = Media(file=file)
                avatar.save()

                # Associate the User instance with the Media instance
                user.avatar = avatar

            # Save user after the updates
            user.save()
            return redirect('profile')
        else:
            # If the form is not valid, print out the form errors
            print(form.errors)
    else:
        form = UserUpdateForm(instance=request.user)
    return render(request, 'main/editprofile.html', {'form': form})


def logoutUser(request):
    logout(request)
    return redirect('home')

templates/main/aboutus.html
{% extends './base.html' %}
{% load static %}

{% block title %}
About Us page
{% endblock title %}

{% block style %}
<link rel="stylesheet" href="{% static 'style/userprofile.css' %}">
{% endblock style %}

{% block content %}
<div class="profile">
    <div class="container">
        <div class="profile-avatar">
            <img src="{% static 'img/IMG_0045.jpg' %}" alt="Profile Picture"/>
        </div>
        <div class="profile-info">
            <h3>Kianmehr Haddad Zahmatkesh</h3>
            <p>Web Developer | Adventurer</p>
        </div>
        <div class="profile-about">
            <h2>My journey</h2>
            <div>
                Welcome to Dine Discover, your one-stop solution for discovering the best restaurants in town!
            </div>
            
            <div>
                Dine Discover began as a personal project, an avenue for me to hone my skills in web development.
                As I started building the site, I realized that this training exercise could actually be turned into a useful tool.
                I saw potential in creating a platform where people could easily find restaurants, cafes, and bars, as well as share their own experiences and reviews.
            </div>
            
            <div>
                The journey from a personal project to a fully functional website was a challenging yet rewarding experience.
                As I delved deeper into the development, I explored different frameworks, navigated through complex problems, and came out the other side with a wealth of knowledge and experience.
                It was a deep dive into the intricacies of web development, and every step was an opportunity to learn, grow, and improve.
            </div>
            
            <div>
                What started as a training exercise turned into a passion project.
                It was the perfect blend of my love for food and tech.
                Each restaurant added, each review shared, each visitor who found their perfect dining spot, fueled my passion to make Dine Discover better.
            </div>
            
            <div>
                But our journey doesn't stop here. The experiences I've gained while developing this website have been invaluable, and I look forward to utilizing these skills in improving Dine Discover and developing new websites.
                We have big plans for the future, and I'm excited to bring them to life.
            </div>
            
            <div>
                I invite you to be a part of our journey. Together, let's make discovering food an exciting adventure!
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <script
      src="https://kit.fontawesome.com/bc8482cdd5.js"
      crossorigin="anonymous"
    ></script>
    <link rel="stylesheet" href="{% static 'style/style.css' %}" />
    {% block style %} {% endblock style %}
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap"
      rel="stylesheet"
    />
    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include './header.html' %} {% block content %} {% endblock content %} 
    {% include './footer.html' %}
  </body>
</html>
<script>
document.addEventListener("DOMContentLoaded", function () {
    if (localStorage.getItem("theme") === "dark") {
        document.body.classList.add("dark-theme");
        document.body.classList.remove("light-theme");
        document.getElementById("darkmode-toggle").checked = true;
      } 
      else {
        document.body.classList.add("light-theme");
        document.body.classList.remove("dark-theme");
        document.getElementById("darkmode-toggle").checked = false;
      }
  });

  function toggleMenu() {
    if (localStorage.getItem("theme") === "dark") {
      document.body.classList.remove("dark-theme");
      document.body.classList.add("light-theme");
      localStorage.setItem("theme", "light");
    } else {
      document.body.classList.remove("light-theme");
      document.body.classList.add("dark-theme");
      localStorage.setItem("theme", "dark");
    }
  }
</script>

templates/main/contact.html
{% extends './base.html' %}
{% load static %}

{% block title %}
contact page
{% endblock title %}

{% block style %}
<link rel="stylesheet" href="{% static 'style/userprofile.css' %}">
{% endblock style %}

{% block content %}
<div class="profile">
    <div class="container">
        <div class="profile-info">
            <h3>Contact Us</h3>
            <p>We'd love to hear from you!</p>
        </div>

        <div class="profile-about">
            <h2>Our Details</h2>
            <div>
                <strong>Email:</strong> haddad.kianm@gmail.com
            </div>
            <div>
                <strong>Github:</strong> <a href="https://github.com/kianmhz" target="_blank">Kianmhz</a>
            </div>
            <div>
                <strong>LinkedIn:</strong> <a href="https://linkedin.com/in/kianmhz" target="_blank">Kianmhz</a>
            </div>
            <div>
                <strong>Twitter:</strong> <a href="https://twitter.com/Kianmehrhz" target="_blank">@Kianmehrhz</a>
            </div>
            <div>
                <strong>Instagram:</strong> <a href="https://instagram.com/Kianmhz" target="_blank">@Kianmhz</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/main/editprofile.html
{% extends './base.html' %}
{% load static %}

{% block title %}
info page
{% endblock title %}

{% block style %}
<link rel="stylesheet" href="{% static 'style/userprofile.css' %}">
{% endblock style %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="profile">
        <div class="container">
            <div class="editProfileAvatar">
                <label class="edit-label" for="id_avatar">
                  <span>Change Image</span>
                </label>
                {{ form.avatar }}
                <img src="{{ user.avatar.file.url|default:'../static/img/user.png' }}" id="output"/>
            </div>

            <div class="editProfileGroup">
                <label for="username">Username:</label>
                {{ form.username }}
            </div>

            <div class="editProfileGroup">
                <label for="name">Name:</label>
                <div class="name-field">
                    {{ form.first_name }}
                    {{ form.last_name }}
                </div>
            </div>

            <div class="editProfileGroup">
                <label for="about">About:</label>
                {{ form.about }}
            </div>
            <button type="submit" class="main-button"><span>Update Profile</span></button>
        </div>
    </div>
</form>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        function readURL(input) {
          if (input.files && input.files[0]) {
            var reader = new FileReader();
        
            reader.onload = function(e) {
              document.getElementById('output').src = e.target.result;
            }
      
            reader.readAsDataURL(input.files[0]);
          }
        }
      
        document.getElementById('id_avatar').addEventListener('change', function() {
          readURL(this);
        });
      });
</script>
{% endblock content %}

templates/main/footer.html
<footer>
    <div class="main-footer">
        <div class="container">
            <div>
                <span><strong>About Website</strong></span>
                <a href="{% url 'about' %}">About Us</a>
                <a href="{% url 'contact' %}">Contact</a>
                <a href="#">Culture</a>
                <a href="#">Blog</a>
                <a href="#">Careers</a>
                <a href="#">Security</a>
            </div>
            <div>
                <span><strong>For Foodies</strong></span>
                <a href="#">Code of Conduct</a>
                <a href="#">Community</a>
                <a href="#">Verified Users</a>
                <a href="#">Blogger Help</a>
                <a href="#">Developers</a>
                <a href="#">Mobile Apps</a>
            </div>
            <div>
                <span><strong>For Restaurants</strong></span>
                <a href="#">Add a Restaurant</a>
                <a href="#">Claim your Listing</a>
                <a href="#">Business App</a>
                <a href="#">Business Owner Guidlines</a>
                <a href="#">Business Blog</a>
                <a href="#">Restaurant Widgets</a>
            </div>
            <div>
                <span><br></span>
                <a href="#">Products for Businesses</a>
                <a href="#">Advertise</a>
                <a href="#">Order</a>
                <a href="#">Book</a>
                <a href="#">Trace</a>
            </div>
        </div>
    </div>
    <div class="copyright-section">
        <div class="container">
            <div class="policy">
                <a href="#">&copy; 2023 Kianmhz. All rights reserved.</a>
                <a href="#">Privacy</a>
                <a href="#">Terms</a>
                <a href="#">API Policy</a>
                <a href="#">CSR</a>
                <a href="#">Sitemap</a>
            </div>
            <div class="social">
                <i class="fa-brands fa-meta"></i>
                <i class="fa-brands fa-twitter"></i>
                <i class="fa-brands fa-instagram"></i>
            </div>
        </div>
    </div>
</footer>

templates/main/header.html
<header>
    <div class="container">
        <div class="left-section">
            <a href="{% url 'home' %}">
                <div class="logo">D</div>
            </a>
            <div class="logo-text">
                <span>Dine</span>
                Discover
            </div>
        </div>
        <div class="right-section">
            <a href="#">Breakfast</a>
            <a href="#">Lunch</a>
            <a href="#">Dinner</a>
            <a href="#">Cafes</a>
            <div class="darkmode">
                <input type="checkbox" id="darkmode-toggle">
                <label for="darkmode-toggle" onclick="toggleMenu()">
                    <svg class="sun" xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 512 512"><!--! Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M375.7 19.7c-1.5-8-6.9-14.7-14.4-17.8s-16.1-2.2-22.8 2.4L256 61.1 173.5 4.2c-6.7-4.6-15.3-5.5-22.8-2.4s-12.9 9.8-14.4 17.8l-18.1 98.5L19.7 136.3c-8 1.5-14.7 6.9-17.8 14.4s-2.2 16.1 2.4 22.8L61.1 256 4.2 338.5c-4.6 6.7-5.5 15.3-2.4 22.8s9.8 13 17.8 14.4l98.5 18.1 18.1 98.5c1.5 8 6.9 14.7 14.4 17.8s16.1 2.2 22.8-2.4L256 450.9l82.5 56.9c6.7 4.6 15.3 5.5 22.8 2.4s12.9-9.8 14.4-17.8l18.1-98.5 98.5-18.1c8-1.5 14.7-6.9 17.8-14.4s2.2-16.1-2.4-22.8L450.9 256l56.9-82.5c4.6-6.7 5.5-15.3 2.4-22.8s-9.8-12.9-17.8-14.4l-98.5-18.1L375.7 19.7zM269.6 110l65.6-45.2 14.4 78.3c1.8 9.8 9.5 17.5 19.3 19.3l78.3 14.4L402 242.4c-5.7 8.2-5.7 19 0 27.2l45.2 65.6-78.3 14.4c-9.8 1.8-17.5 9.5-19.3 19.3l-14.4 78.3L269.6 402c-8.2-5.7-19-5.7-27.2 0l-65.6 45.2-14.4-78.3c-1.8-9.8-9.5-17.5-19.3-19.3L64.8 335.2 110 269.6c5.7-8.2 5.7-19 0-27.2L64.8 176.8l78.3-14.4c9.8-1.8 17.5-9.5 19.3-19.3l14.4-78.3L242.4 110c8.2 5.7 19 5.7 27.2 0zM256 368a112 112 0 1 0 0-224 112 112 0 1 0 0 224zM192 256a64 64 0 1 1 128 0 64 64 0 1 1 -128 0z"/></svg>
                    <svg class="moon" xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 384 512"><!--! Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M144.7 98.7c-21 34.1-33.1 74.3-33.1 117.3c0 98 62.8 181.4 150.4 211.7c-12.4 2.8-25.3 4.3-38.6 4.3C126.6 432 48 353.3 48 256c0-68.9 39.4-128.4 96.8-157.3zm62.1-66C91.1 41.2 0 137.9 0 256C0 379.7 100 480 223.5 480c47.8 0 92-15 128.4-40.6c1.9-1.3 3.7-2.7 5.5-4c4.8-3.6 9.4-7.4 13.9-11.4c2.7-2.4 5.3-4.8 7.9-7.3c5-4.9 6.3-12.5 3.1-18.7s-10.1-9.7-17-8.5c-3.7 .6-7.4 1.2-11.1 1.6c-5 .5-10.1 .9-15.3 1c-1.2 0-2.5 0-3.7 0c-.1 0-.2 0-.3 0c-96.8-.2-175.2-78.9-175.2-176c0-54.8 24.9-103.7 64.1-136c1-.9 2.1-1.7 3.2-2.6c4-3.2 8.2-6.2 12.5-9c3.1-2 6.3-4 9.6-5.8c6.1-3.5 9.2-10.5 7.7-17.3s-7.3-11.9-14.3-12.5c-3.6-.3-7.1-.5-10.7-.6c-2.7-.1-5.5-.1-8.2-.1c-3.3 0-6.5 .1-9.8 .2c-2.3 .1-4.6 .2-6.9 .4z"/></svg>
                </label>
            </div>
            {% if user.is_authenticated %}
            
            <a href="{% url 'profile' %}">
                <button class="joinus-button"><strong>Profile</strong></button>
            </a>
            <a href="{% url 'logout' %}"><i class="fa-solid fa-right-from-bracket"></i></a>
            {% else %}
            <a href="{% url 'login_register' %}">
                <button class="joinus-button"><strong>Join Us</strong></button>
            </a>
            {% endif %}
        </div>
    </div>
</header>

templates/main/home.html
{% extends './base.html' %}
{% load static %}

{% block title %}
main page
{% endblock title %}

{% block content %}
{% if user.is_authenticated %}
<div class="slider">
    <div>Welcome back,<br><strong>{{user.first_name}}</strong><br></div>
</div>
{% else %}
<div class="slider">
    <div>Find the best restaurants,<br>cafes, and bars in<br><strong>London</strong></div>
</div>
{% endif %}
<div class="search">
    <form class="container" method="GET" action="{% url 'home' %}">
        <input class="search-bar" type="text" name="q" placeholder="Find a Restaurant...">
        <button class="main-button">Find Out</button>
    </form>
</div>

<section class="restaurants">
    <div class="title">
        <div>Most Visited Places</div>
        <span>Discover top-rated local restaurants, cafes, and bars</span>
    </div>

    <div class="restaurants-grid container">
        {% for restaurant in restaurants %}
        <div class="restaurants-info">
            <a href="{% url 'info' %}">
                <div class="thumbnail-container">
                    <img class="thumbnail" src="{{restaurant.image}}">
                    <div class="restaurants-info-position">
                        <div class="restaurants-name">{{ restaurant.name }}</div>
                        <div class="restaurants-location">{{ restaurant.address }}</div>
                    </div>
                </div>
            </a>
            <div class="rating">
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <div>(review 20)</div>
            </div>
        </div>
        {% endfor %}
    </div>
</section>
{% endblock content %}

templates/main/reviews.html
{% extends './base.html' %}
{% load static %}

{% block title %}
info page
{% endblock title %}

{% block style %}
<link rel="stylesheet" href="{% static 'style/userprofile.css' %}">
{% endblock style %}

{% block content %}
<div class="review-section">
    <div class="container">
        <h2>{{user.username}} Reviews</h2>
        {% for review in reviews %}
            <div class="review">
                <h3>{{ review.restaurant.name }}</h3>
                <p>{{ review.content|truncatewords:40 }}</p>
                <a href="{% url 'review_detail' review.id %}">Read more</a>
            </div>
        {% empty %}
            <div class="review">
                <span>No reviews yet.</span>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

templates/main/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign Up Page</title>
    <link rel="stylesheet" href="{% static 'style/auth.css' %}">
</head>
<body>
    <div class="slider">
        <form action="" method="POST">
            {% csrf_token %}
            <div class="login-form">
                <h1>Welcome to Dine Discover</h1>
                <div class="search">
                    <div class="name-field">
                        {{form.first_name}}
                        {{form.last_name}}
                    </div>
                </div>
                <div class="search">
                    {{form.username}}
                </div>
                <div class="search">
                    {{form.email}}
                </div>
                <div class="search">
                    {{form.password1}}
                </div>
                <div class="search">
                    {{form.password2}}
                </div>
                <button type="submit" class="login-button">Sign Up</button>
                <span>Already have an account? <a href="/login">Login here</a></span>
            </div>
        </form>
    </div>
</body>
</html>

templates/main/user_auth_base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" type="text/css" href="{% static 'style/auth.css' %}"/>
    <script src="https://kit.fontawesome.com/bc8482cdd5.js" crossorigin="anonymous"></script>
  </head>

  <body class="slider">
    <div class="container" id="container">
      {% if request.path == "/login_register" %}
      <a href={% url "home" %}><div class="back-icon"><i class="fa-solid fa-arrow-left"></i></div></a>
      {% elif request.path|slice:":6" == "/reset" %}
      <a href={% url "login_register" %}><div class="back-icon"><i class="fa-solid fa-arrow-left"></i></div></a>
      {% endif %}
      {% block content %}
      {% endblock content %}
    </div>
  </body>
    {% block js %}
    {% endblock js %}
</html>

<style>
  .back-icon {
    position: absolute;
    z-index: 100000;
    top: 20px;
    left: 20px;
    font-size: 30px;
    cursor: pointer;
  }
</style>